import type { MetadataRoute } from "next";

// Makes the CRM an installable, full-screen app on phones/tablets ("Add to
// Home Screen") so the crew and sales team can run it like a native app in the
// field. Icons are generated by app/icon.tsx and app/apple-icon.tsx.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Floor King CRM — Cleveland Floor King",
    short_name: "Floor King",
    description:
      "Run the whole flooring business from the field — leads, estimates, jobs, schedule, and inventory.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#0b0c10",
    theme_color: "#0b0c10",
    categories: ["business", "productivity"],
    icons: [
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
