/**
 * Flooring knowledge engine — the rules the guided estimate asks by.
 *
 * Flooring Family → Installation System → Relevant Questions → Derived
 * values → Generated lines → Warnings → Scope notes.
 *
 * Catalog categories are not invented here. Families map onto the existing
 * ProductCategory set (carpet, lvp, hardwood, laminate, tile, vinyl, …).
 */

export {
  SURFACE_TYPE_LABELS,
  LEGACY_LVP_VINYL_LABEL,
  INSTALL_METHOD_LABELS,
  CONDITION_CONFIDENCE_LABELS,
  familyFromCatalogCategory,
  familyFromSurfaceLabel,
  hardwoodConstructionFromLabel,
  catalogCategoryForFamily,
  installSystemFromLabel,
  permittedInstallSystems,
  installMethodOptionsFor,
  installMethodOptionsForFamilies,
  hardSurfaceInstallMethodOptions,
  solePermittedInstallSystem,
  leftoverIllegalSoleInstallLabels,
  coalesceSoleInstallSystem,
  stripIllegalInstallSystems,
  isHardSurfaceFamily,
  jobNeedsMixedInstallMethodPicks,
  isRollGoodsFamily,
  carpetInstallSystemsFromLabels,
  rollGoodsNeedCuts,
  isBoxedFamily,
  isHardSurfaceStairFamily,
  jobNeedsHardSurfaceStairTrim,
  flooringFamiliesFromCategories,
  mergeFlooringFamilies,
  unscopedProductFamilies,
  billsBySqydFamily,
  profileForFamily,
  defaultWastePctForFamily,
  familyLabel,
  hardwoodConstructionFromSpecies,
  prepQuantitiesAreFinal,
  prepQuantitySuffix,
  type FlooringFamily,
  type HardwoodConstruction,
  type InstallSystem,
  type ConditionConfidence,
} from "./families";

export { matchesShowIf, isShowIfClause, showIfReferencedKeys } from "./show-if";

export {
  answerGateValues,
  coerceYesNoChoiceAnswer,
  synthesizeStairGate,
  stairStepCountFromAnswer,
  stairStepCountFromAnswers,
  applyHardSurfaceStairTrimFill,
  HARD_SURFACE_STAIR_TRIM_LABELS,
  answersHaveTrimType,
  HS_TRANSITION_OPTION_TO_TRIM,
  HS_BASE_OPTION_TO_TRIM,
  trimLabelsFromPicks,
  applyTrimTypeSeed,
  presentTrimTypes,
  keyedChoiceSelections,
  annotateRemovalDescription,
  jobIsNewConstruction,
  jobIsExclusiveNewConstruction,
  labelsAreNewConstruction,
  labelsAreNewConstructionOnly,
  tileJobIsWallOnly,
  labelsAreWallOnly,
  jobIsVacant,
  labelsAreVacant,
  labelsAreConcreteOnly,
  labelsAreWoodDeckOnly,
  labelsAreExistingFlooringOnly,
  jobIsExclusiveConcreteSubstrate,
  WORK_TYPE_NEW_CONSTRUCTION,
  type GateAnswer,
  type StairAnswerKind,
  type HardSurfaceStairTrimLabel,
} from "./answers";

export {
  knowledgeQuestionByKey,
  amountUnitLabelForQuestion,
  estimatorPhaseForQuestion,
  estimatorPhaseRank,
  estimatorPhaseLabel,
  questionPhaseMap,
  sortEstimateQuestions,
  ESTIMATOR_PHASE_ORDER,
  ESTIMATOR_PHASE_LABELS,
  REMOVAL_QUESTION_KEYS,
  NEW_CONSTRUCTION_HIDES_KEYS,
  MERGED_CLIMATE_HIDES_KEYS,
  MERGED_CURB_HIDES_KEYS,
  CARPET_ONLY_HIDES_KEYS,
  DEAD_STAIR_GATE_HIDES_KEYS,
  DEAD_STAIR_FOLLOWUP_HIDES_KEYS,
  TILE_WALL_HIDES_KEYS,
  TILE_THINSET_HIDES_KEYS,
  CARPET_TILE_VAPOR_HIDES_KEYS,
  CONCRETE_HIDES_KEYS,
  WOOD_DECK_MOISTURE_HIDES_KEYS,
  GLUE_WOOD_VAPOR_HIDES_KEYS,
  WOOD_DECK_AQUA_HIDES_KEYS,
  WOOD_DECK_VAPOR_HIDES_KEYS,
  GLUE_EXISTING_VAPOR_HIDES_KEYS,
  EXISTING_FLOOR_AQUA_HIDES_KEYS,
  EXISTING_FLOOR_VAPOR_HIDES_KEYS,
  LOOSE_LAY_VAPOR_HIDES_KEYS,
  NON_VINYL_DEMO_SKIM_HIDES_KEYS,
  NON_HARDWOOD_FASTENER_HIDES_KEYS,
  NON_CARPET_DEMO_PAD_HIDES_KEYS,
  NONE_DEMO_DISPOSAL_HIDES_KEYS,
  FURNITURE_MOVING_KEYS,
  CARPET_TILE_HIDES_KEYS,
  SOLID_HARDWOOD_HIDES_KEYS,
  tileWallHidesPrepOptionLabel,
  tileWallHidesDemoOptionLabel,
  vaporBarrierHidesUnderlaymentOptionLabel,
  type KnowledgeQuestionDef,
  type EstimatorPhase,
  type SortableEstimateQuestion,
} from "./registry";

export {
  measuredArea,
  equivalentSqyd,
  sqydToSqft,
  cartonTakeoff,
  computeMaterialTakeoff,
  padFoamTakeoffLabel,
  takeoffDisplayTitle,
  formatSqft,
  formatSqyd,
  formatEquivalentSqyd,
  builderAreaFallbackLabel,
  ROLL_GOODS_CUTS_MISSING_CAPTION,
  ROLL_GOODS_CUTS_HEADER,
  ROLL_GOODS_CUTS_EMPTY_HINT,
  lineMeasurementsRollTotalLabel,
  questionnaireCutGroupOrderLabel,
  questionnaireCutsGrandOrderLabel,
  formatMeasuredLabel,
  EXTRA_AREA_MEASURED_LABEL,
  EXTRA_AREA_MEASURED_PLACEHOLDER,
  EXTRA_AREA_MEASURED_HINT,
  formatBillingQty,
  formatTakeoffStrip,
  takeoffConceptRows,
  takeoffUnitKeyLabel,
  rollGoodsOrderTbdDescription,
  accessoryUnitForType,
  coerceTrimUnit,
  defaultCutWidthFt,
  enteredCutWidthFt,
  cutWidthChoicesFt,
  billingUnitForCategory,
  areaBillsBySquareYard,
  billingUnitForArea,
  rollGoodsHaveCuts,
  areaDerivedMaterialAllowed,
  areaDerivedMaterialQty,
  measuredInstallLaborAllowed,
  configuredInstallRate,
  materialWastePctForEmit,
  type MeasuredArea,
  type CartonTakeoff,
  type MaterialTakeoff,
  type OrderBasis,
  type ComputeTakeoffInput,
  type TakeoffConceptRow,
} from "./quantities";

export {
  measuredRectsFromRooms,
  seamImplication,
  rollGoodsSeamWarnings,
  type MeasuredRect,
  type SeamKind,
} from "./layout";

export {
  emptyInstallContext,
  installContextFromValByKey,
  withProductFamilies,
  finalizeInstallContext,
  synthesizeSoleInstallMethod,
  DEFAULT_KNOWLEDGE_WHEN,
  KNOWLEDGE_QUESTIONS,
  knowledgeWhenApplies,
  knowledgeClauseApplies,
  questionKnowledgeWhen,
  questionApplies,
  questionPurpose,
  knowledgeHelpFor,
  knowledgeWarnings,
  mixedJobAssignmentGaps,
  visibleKnowledgeKeys,
  resolveQuestionVisibility,
  substrateLabelMatches,
  jobNeedsAcclimationClimate,
  installNeedsAcclimationClimate,
  climateControlConfirmed,
  jobHasNonTileFloorFamily,
  jobIsExclusiveTile,
  jobIsExclusiveWallTile,
  jobIsExclusiveCarpetTile,
  jobIsExclusiveCarpetTileOnly,
  jobIsExclusiveSolidHardwood,
  jobIsExclusiveConcrete,
  jobHasHardSurfaceInstallScope,
  jobHasCarpetInstallScope,
  jobIsExclusiveCarpetOnly,
  jobHidesDeadStairGate,
  jobHidesDeadStairFollowups,
  jobHidesSlabMoistureOnWoodDeck,
  jobHidesVaporOnGlueWoodDeck,
  jobHidesVaporOnWoodDeck,
  jobHidesAquaBarOnGlueWoodDeck,
  jobHidesVaporOnGlueExistingFloor,
  jobHidesVaporOnExistingFloor,
  jobHidesAquaBarOnGlueExistingFloor,
  jobHidesAquaBarOnExistingFloor,
  jobHidesVaporOnLooseLay,
  jobHidesVinylSkimOnNonVinylDemo,
  jobHidesFastenersOnNonHardwood,
  jobHidesPadOnNonCarpetDemo,
  jobHidesDisposalOnNoDemo,
  jobAllowsFloatingVaporUnderlayment,
  choiceOptionApplies,
  type InstallContext,
} from "./rules";

export {
  buildSalespersonReview,
  reviewToJobNotes,
  mergeReviewWarnings,
  familyListLabel,
  formatFtIn,
  formatDimensionPair,
  confidenceFromLabel,
  groupMeasuredSqftByLabel,
  groupMeasuredSqftByFamily,
  measuredSqftForFamilyTakeoff,
  measuredSqftForFamiliesTakeoff,
  measuredSqftForPrepTakeoff,
  measuredSqftForQuestionCover,
  roomsAssignedToFamilies,
  roomsForPrepTakeoff,
  emitAreaSqftForQuestion,
  deliveryAddonCost,
  reviewBucketForQuestion,
  type ReviewRoom,
  type ReviewSection,
  type ReviewBucket,
  type SalespersonReview,
} from "./takeoff";
